### ISSUE TITLE
sts-wire complains while restarting after the first setup

### ISSUE THREAD

**Issue by spigad** [DODAS-TS/sts-wire#7]
after a first installation , sts-wire is not starting anymore  and complain with oauth error ( seems like the callback url previously cached is not ok anymore) 

ERROR: 
OAuth Error

error="invalid_grant", error_description="Invalid redirect: http://localhost:54452/oauth2/callback does not match one of the registered values: [http://localhost:53742/oauth2/callback]"

**Comment by MircoT** [comment]
Should be solved since `v1.3.2`
